name: personal_profile
description: "A Personal Profile App showcasing basic Flutter layouts and responsive UI design."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/profile.jpg
  #   - images/
